name-template: 'v$RESOLVED_VERSION 📬'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚨 BREAKING CHANGES 🚨'
    labels:
      - 'BREAKING CHANGE'
  - title: '🚀 New Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: '🛠️ Other Changes'
    labels:
      - 'chore'
      - 'refactor'
      - 'documentation'
      - 'style'
      - 'test'
      - 'build'
      - 'performance'
      - 'revert'
      - 'dependencies'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'BREAKING CHANGE'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'fix'
      - 'bug'
      - 'refactor'
      - 'chore'
  default: patch
autolabeler:
  - label: 'BREAKING CHANGE'
    title:
      - '/!:/i'

  - label: 'chore'
    title:
      - '/^chore/i'

  - label: 'documentation'
    title:
      - '/^doc/i'

  - label: 'fix'
    title:
      - '/^fix/i'
      - '/^bug/i'

  - label: 'build'
    title:
      - '/^build/i'
      - '/^ci/i'

  - label: 'refactor'
    title:
      - '/^refactor/i'

  - label: 'feature'
    title:
      - '/^feature/i'
      - '/^feat/i'

  - label: 'style'
    title:
      - '/^style/i'

  - label: 'performance'
    title:
      - '/^perf/i'

  - label: 'test'
    title:
      - '/^test/i'

  - label: 'revert'
    title:
      - '/^revert/i'

template: |
  ## 🔔 Token API new Release 📬

  $CHANGES